### ISSUE TITLE
Undefined index: error

### ISSUE THREAD

**Issue by lindseydiloreto** [moltin/php-sdk#12]
Using this code:

    \Currency::Create([
        'title'       => 'Example Currency',
        'slug'        => 'example-currency',
        'code'        => 'EXM',
        'format'      => '!{price}',
        'enabled'     => true,
        'description' => 'Testing an example currency'
    ]);

... generates an error:

    Notice: Undefined index: error in /vendor/moltin/php-sdk/src/Moltin/SDK/SDK.php on line 223
    Fatal error: Uncaught thrown in /vendor/moltin/php-sdk/src/Moltin/SDK/SDK.php on line 226

Am I doing something wrong, or is this a bug in the SDK?

**Comment by Nessworthy** [comment]
Here's the code reference: https://github.com/moltin/php-sdk/blob/version1/src/Moltin/SDK/SDK.php#L223

Seems like an API request returned with an error, but the error parser couldn't identify it.
The fatal error is due to not using a try/catch block for the call.

Not sure what is causing the error in the first place.

**Comment by outrunthewolf** [comment]
Yes, it seems so. i'm looking into the issue now.

**Comment by outrunthewolf** [comment]
Couple of issues here actually. 

Apologies for the delay, we're testing a patch for the API and the SDK.

**Comment by lindseydiloreto** [comment]
No worries! I appreciate you looking into it. :)

**Comment by outrunthewolf** [comment]
These issues should be patched now up for API and SDK. Let me know how you get on, i'll keep this open till confirmed.

**Comment by lindseydiloreto** [comment]
Looks like the API fix did it! I haven't even updated my SDK yet, and it's already working properly.

Thanks! :)
