### ISSUE TITLE
Tax Band is required?

### ISSUE THREAD

**Issue by lindseydiloreto** [moltin/php-sdk#13]
When I try to update a product, it tells me this:

> Tax Band is required

Specifically, this code:

```
\Product::Update(964964820061258459, [
    'title' => 'Awesomesauce!',
]);
```

... produces this error message:

```
Fatal error: Uncaught Tax Band is required thrown in /vendor/moltin/php-sdk/src/Moltin/SDK/SDK.php on line 226
```

Seems silly to me to require the Tax Band every time I want to make an adjustment to a product. Is it safe to assume that this is a bug?

**Comment by outrunthewolf** [comment]
Its not a bug. But yes we also think some of the required fields on PUT are un-needed.

We're hoping to push an update this coming week to change this for the products endpoint and a few more.

I'll keep this thread open and update you on progress.

**Comment by lindseydiloreto** [comment]
Excellent, thank you! :)
