### ISSUE TITLE
Not all the Images from a Flow are shown on the Images tab

### ISSUE THREAD

**Issue by zot24** [moltin/php-sdk#22]
If add an Image on the field `cover` which is a `file type field` the image won't be shown on the `Images tab`

<img width="1246" alt="screen shot 2015-09-30 at 16 44 22" src="https://cloud.githubusercontent.com/assets/678498/10198290/4dcbe128-6793-11e5-86b0-a2102ad5dc9c.png">

<img width="1242" alt="screen_shot_2015-09-30_at_16_44_17" src="https://cloud.githubusercontent.com/assets/678498/10200237/13bae740-679d-11e5-93e9-ca09503a75d3.png">

**Comment by outrunthewolf** [comment]
nice spot :+1:

**Comment by outrunthewolf** [comment]
Redact my last comment.

I wasn't reading properly, this is intended behaviour (at the moment).

Because the cover image is a different field to the product images, they won't be shown on the images tab.

**Comment by zot24** [comment]
:+1: thanks for the clarification
