### ISSUE TITLE
PHP Authentication failing

### ISSUE THREAD

**Issue by Djminisite06** [moltin/php-sdk#50]
When attempting to access the PHP SDK any attempts to use the API result in:
`Fatal error: Uncaught You haven't authenticated yet thrown in /Volumes/1GB_Temp2/server/_includes/vendor/moltin/php-sdk/src/SDK.php on line 198`
despite utilsing 
`Moltin::Authenticate('ClientCredentials', [
    	'client_id'     => ' --- ',
	'client_secret' => ' --- '
]);` as recommended in the quick start documentation.

Thanks

**Comment by zot24** [comment]
Could you please double check few things for me first:

1.- Do you have the correct `client_id` and `client_secret`?

To verify this you can try to get an access token using CURL like:

```
curl -X POST https://api.molt.in/oauth/access_token \
	-d "client_id={client id}" \
	-d "client_secret={client secret}" \
	-d "grant_type=client_credentials"
```

> Note: you can check the full documentation in here: https://docs.moltin.com/authenticate/

2.- Have you imported the Facade for Moltin?

```
  $result = \Moltin\SDK\Facade\Moltin::Authenticate('ClientCredentials', [
    'client_id'     => 'my_super_secret_client_id',
    'client_secret' => 'my_super_secret_client_secret'
  ]);
```

3.- And last could you please check that whatever the `Authenticate` method it's giving you back it's `true`

Hope that helps, thanks let us know :)

**Comment by Djminisite06** [comment]
1. - I've got the right client_id and client_secret - I've just checked them both in my account and using CURL which granted a bearer_token.

2. - I've tried the way recommended in the API reference, and the way recommended above, and recieve the same error both times

3. - It's actually returning false

Thanks

**Comment by zot24** [comment]
Could you please let me know which version of the PHP-SDK are you using?

**Comment by Djminisite06** [comment]
1.3

**Comment by zot24** [comment]
I'm running out of ideas, just test it from scratch with a base Laravel app and it just work for me I can only just of two things ATM:

1. I know it may sound stupid but when you say `'client_id' => ' --- '`, are you adding those white spaces around your `client_id`?

2. Have you initialised the constructor of the SDK with your `storage` and `request` instance?

```
use Moltin\SDK\Request\CURL as Request;
use Moltin\SDK\Storage\Session as Storage;

$moltin = new \Moltin\SDK\SDK(new Storage(), new Request());
```

> I don't need to do that because I'm using Laravel and it will resolve it and injected for me

How are you using the SDK? which framework? which kind of app are you building?

**Comment by zot24** [comment]
3. Just came to my mind (actually to @Jmz mind) do you have CURL installed? it's a dependency of the SDK

**Comment by Djminisite06** [comment]
1 - No white spaces, just from blanking them out for posting on here
2 - Yes, copied and pasted the code above into a new blank project, and still encountering errors? I'm literally importing the SDK via Composer and using it directly in the PHP backend?
3 - Yes I do, I used it to check that I could generate an access token earlier.

**Comment by zot24** [comment]
The only thing we could do is if you send me the full code you are using and I'll give it a try to see what could be possible wrong as well as you could try to send me your `store_id` and your credentials as well as so I'll double check those on the database. If you jump into our Slack channel https://moltin.com/community you can PM me those details so I can have a look to it for you.

Just let me know

**Comment by basistom** [comment]
Any updates here? Having the same issue.

**Comment by outrunthewolf** [comment]
This issue ended up as  the SDK not being implemented properly.

**Comment by basistom** [comment]
Ok, when was the problem fixed? I tried dev-master and 1.3 and the authentication still returns false:

`Fatal error: Uncaught exception Moltin\SDK\Exception\InvalidRequestException with message You haven't authenticated yet thrown in composer/vendor/moltin/php-sdk/src/SDK.php on line 198`

**Comment by outrunthewolf** [comment]
The problem means you're calling a request for a part of the API, before you've authenticated. So its to do with how the SDK is implemented in your code. Might be worth circulating your code on a gist or something to see where the issue is.

**Comment by basistom** [comment]
I missunderstood that. At least I only have the following lines as described in the documentation where $sdk returns false and $products leads to the described error:

```
$sdk = \Moltin\SDK\Facade\Moltin::Authenticate('ClientCredentials', [
    'client_id'     => $dc->activeRecord->moltinClientID,
    'client_secret' => $dc->activeRecord->moltinClientSecret
]);
dump($sdk);

$products = \Moltin\SDK\Facade\Product::Listing();
dump($products);
```

**Comment by outrunthewolf** [comment]
Have you done this bit?

```
use Moltin\SDK\Request\CURL as Request;
use Moltin\SDK\Storage\Session as Storage;

$moltin = new \Moltin\SDK\SDK(new Storage(), new Request());
```

as explained here: https://github.com/moltin/php-sdk#instantiating-the-package

**Comment by basistom** [comment]
Makes no difference if it's in or not. Tried it with the following version, too:

```
use Moltin\SDK\Request\CURL as Request;
use Moltin\SDK\Storage\Session as Storage;
$moltin = new \Moltin\SDK\SDK(new Storage(), new Request());

$sdk = \Moltin\SDK\Facade\Moltin::Authenticate('ClientCredentials', [
    'client_id'     => $dc->activeRecord->moltinClientID,
    'client_secret' => $dc->activeRecord->moltinClientSecret
]);
dump($sdk);

$products = \Moltin\SDK\Facade\Product::Listing();
dump($products);
```

**Comment by outrunthewolf** [comment]
What does dump output? 

And are you sure the client_id and secret are set?

**Comment by basistom** [comment]
dump($sdk) =>
`bool(false)`

dump($moltin) =>
```
Moltin\SDK\SDK Object
(
    [version] => v1
    [url] => https://api.molt.in/
    [auth_url] => http://auth.molt.in/
    [methods] => Array
        (
            [0] => GET
            [1] => POST
            [2] => PUT
            [3] => DELETE
        )

    [currency] => 
    [language] => 
    [store] => Moltin\SDK\Storage\Session Object
        (
        )

    [request] => Moltin\SDK\Request\CURL Object
        (
            [url] => 
            [method] => 
            [code] => 
            [time] => 
            [header] => 
            [curl:protected] => 
            [options:protected] => Array
                (
                )

        )

    [token:protected] => 
    [refresh:protected] => 
    [expires:protected] => 
)
```

Yes - client_id and secret are set and correct.

**Comment by outrunthewolf** [comment]
Are you using WAMP or MAMP by any chance?

**Comment by basistom** [comment]
Nope. Working local on OSX with native Apache 2.4, PHP 5.6, MySQL.
Can cause the *.local-domain any problems?

Using the following CURL returns valid authentificationdata:
```
$clientId = <ClientID>;
$clientSecret = <ClientSecret>;

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL,"https://api.molt.in/oauth/access_token");
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,"grant_type=client_credentials&client_id={$clientId}&client_secret={$clientSecret}");

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$result = curl_exec($ch);

var_dump($result);
var_dump(curl_errno($ch));
var_dump(curl_error($ch));

curl_close ($ch);
```

**Comment by outrunthewolf** [comment]
Thats good. I thought it might be using an invalid SSL or TLS protocol.

I would advise digging into the CURL class here:
 - https://github.com/moltin/php-sdk/blob/master/src/Request/CURL.php

And the client credentials class here:
 - https://github.com/moltin/php-sdk/blob/master/src/Authenticate/ClientCredentials.php#L53

During the request cycle to see the exact error you're getting. I'd be interested in seeing what comes back.

**Comment by basistom** [comment]
Woop Woop.

I dumped the curl_error($this->curl) in https://github.com/moltin/php-sdk/blob/master/src/Request/CURL.php on line 121 and got the following error:
`SSL: CA certificate set, but certificate verification is disabled`

After some googling I found the following working solution:
http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error/26538127#26538127

**Comment by Jmz** [comment]
For future reference, the current SDK will return false if the authentication fails. Normally this is because of an SSL issue (incorrect protocols, missing certificates etc.).  You can use this script to test the authentication outside of the SDK, it will also dump out any error messages: 

```
<?php

$clientId = 'CLIENTID';
$clientSecret = 'CLIENTSECRET';

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL,"https://api.molt.in/oauth/access_token");
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,"grant_type=client_credentials&client_id={$clientId}&client_secret={$clientSecret}");

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$result = curl_exec($ch);

var_dump($result);
var_dump(curl_errno($ch));
var_dump(curl_error($ch));

curl_close ($ch);
```
